gschup/bevy_ggrs

- examples/box_game/box_game_p2p.rs
- examples/box_game/box_game_spectator.rs
- examples/box_game/box_game_synctest.rs
- src/lib.rs
Instead of a System.
Means you don't need to call .system() on the input system function.
> refactor!: Make with_input_system take an IntoSystem

- Cargo.toml
- examples/README.md
- examples/box_game/box_game.rs
- examples/box_game/box_game_synctest_checksum.rs
This PR adds an example to compute a checksum for types that don't support reflect/hashing (floats, bevy::Transform, ...)
This checksum can be checked by synctest to detect mismatches
> Example: add checksum example for non reflect types

- src/ggrs_stage.rs
- src/lib.rs
i.e.
commands.stop_session()
With this change it's possible to stop and start a new session without
recreating the bevy app.
The implementation is messy (with the marker resource), but it was the
easiest thing to do that I could think of at the moment. At least it's
private.
> feat: Add a way to stop sessions

- Cargo.toml
- examples/box_game/box_game.rs
- src/lib.rs
- src/world_snapshot.rs
I tried to get #25 working and ran into some more issues. I don't know how to add more changes to someone else's PR, so here's a new one.
Apparently a bevy 0.8 TypeRegistry contains some primitive types by default, which caused a "Unregistered Type in GGRS Type Registry" panic. I couldn't find a convenient way to construct a TypeRegistryArc that's actually empty in the new docs, so we have to construct one directly?
I also had into short_name and type_name on a TypeRegistration actually returning different names for the same type. This made write_to_world overlook the components that were saved in the snapshot and delete them from the world instead.
> update for 0.8 with some more changes

- Cargo.toml
This removes this crate's dependency on the Bevy renderers such as `bevy_text`/`ui`/`pbr`, etc.
It definitely was a little unintuitive that the `render` feature is different than the `bevy_render` feature.
> Only Depend on Bevy `bevy_render` not `render`

- src/lib.rs
This makes it easier to make sure your version of `ggrs` is the one compatible with `bevy_ggrs` and saves you from adding an extra dependency to your `Cargo.toml`.
> Re-export `ggrs` Crate

- src/lib.rs
- src/world_snapshot.rs
- tests/entity_maping.rs
Resolves #29.
I haven't really tested this yet, but this should fix entity mapping and hierarchy problems.
If this works it'd be good to have some documentation on how this effects types that store entities.
For instance, if you create your own `Inventory` component that needs to be synced, you must implement and reflect `MapEntities` for it, so that it will get the new entity IDs when the snapshots are applied.
> Map Entity IDs When Writing Snapshot to World

- src/world_snapshot.rs
Removes and re-inserts components during snapshot restore, instead of using `apply()` which does an "update" not a "replace" of the current component data.
For example, an apply() will do an in-place update such that apply an array to an array will add items to the array instead of completely replacing the current array with the new one.
In Jumpy this caused a difficult to trace bug when updating the `Children` component for the Bevy hierarchy, where setting children to an empty array, actually left the component un-modified.
> Fix Component Apply in Certain Cases

- examples/box_game/box_game.rs
- examples/box_game/box_game_p2p.rs
- src/ggrs_stage.rs
This makes it a lot easier to make sense of other bevy log messages and
tell which frame they belonged to.
> Add debug logging on snapshot save and restore

- examples/box_game/box_game.rs
- src/lib.rs
As discussed in #42 .
While this slightly cuts down on the boilerplate, it also slightly obfuscates what type of component (`Rollback`) were adding...
What do you think?
> feat: Add `RollbackIdProvider::next`

- examples/box_game/box_game.rs
- examples/box_game/box_game_p2p.rs
- examples/box_game/box_game_spectator.rs
- examples/box_game/box_game_synctest.rs
- src/ggrs_stage.rs
- src/lib.rs
- tests/entity_mapping.rs
The second commit contains some renaming based on [Rust's API guidelines](https://rust-lang.github.io/api-guidelines/naming.html#casing-conforms-to-rfc-430-c-case). If you are set on the current naming I can revert it :slightly_smiling_face:
> Extension trait to add the GGRS plugin more idiomatically

- src/rollback.rs
I think I just made a mistake in my comment here: https://github.com/gschup/bevy_ggrs/pull/58#discussion_r1173584216
We should just do the same as what `.insert` does.
This makes the following work:
```rust
commands
.entity(tilemap_entity)
.insert(
TilemapBundle {
grid_size,
map_type,
size: tilemap_size,
storage: tile_storage,
texture: TilemapTexture::Single(sprites.white_pixel.clone()),
tile_size,
transform: tilemap_transform.with_z(SHIP_BACKGROUND_LAYER_DEPTH),
..default()
}
)
.add_rollback();
```
> Fix add_rollback command extension

- examples/box_game/box_game.rs
- examples/box_game/box_game_p2p.rs
- examples/box_game/box_game_spectator.rs
- examples/box_game/box_game_synctest.rs
- src/ggrs_stage.rs
- src/lib.rs
- src/world_snapshot.rs
- tests/entity_mapping.rs
- `GgrsPlugin` is now just a regular bevy plugin, and the builder is gone.
- Adds a `ReadInputs` schedule, where inputs should be inserted into a `LocalInputs` resource.
- Registering rollback types are now done on the app instead.
- Adds `LocalPlayers` resource which contains the ggrs handles for the local players
> Make `GgrsPlugin` a regular Bevy plugin

- src/lib.rs
The resource was only added when modifying the FPS, so default FPS didn't work.
This was a regression in 57ceab38
> Fix panic when `set_rollback_schedule_fps` is not called

- Cargo.toml
- src/ggrs_stage.rs
- src/lib.rs
- tests/entity_mapping.rs
This should make writing integration tests easier, since we can then use `TimeUpdateStrategy::ManualDuration`.
> Use Bevy abstractions instead of using `instant` directly

- src/ggrs_stage.rs
The resource is used by the `ReadInputs` schedule so needs to be inserted before running the schedule.
> Fix `LocalPlayers` being empty on first frame

- examples/box_game/box_game.rs
- examples/box_game/box_game_p2p.rs
- examples/box_game/box_game_spectator.rs
- examples/box_game/box_game_synctest.rs
- src/lib.rs
In the `box_game` example, there's a to-do related to `ggrs::Config`:
> `/// TODO: Find a way to hide the state type.`
I've solved this to-do by creating a type `GgrsConfig`:
```rust
#[derive(Debug)]
pub struct GgrsConfig<Input, Address = SocketAddr, State = u8> {
_phantom: PhantomData<(Input, Address, State)>,
}
impl<Input, Address, State> Config for GgrsConfig<Input, Address, State>
where
Self: 'static,
Input: Send + Sync + PartialEq + bytemuck::Pod,
Address: Send + Sync + Debug + Hash + Eq + Clone,
State: Send + Sync + Clone,
{
type Input = Input;
type State = State;
type Address = Address;
}
```
Because `GgrsConfig` is a concrete type, it is allowed to have defaults for the type parameters `Input`, `State`, and `Address` required by `ggrs::Config`. As mentioned in the `box_game` …
> Added Sensible Default `ggrs::Config` type `GgrsConfig`

- src/world_snapshot.rs
- Fixes #63
Before populating the `EntityMap` used during rollback with tracked entities, all entities within the `World` are added as no-op mappings:
```rust
for entity in world.iter_entities() {
let entity = entity.id();
entity_map.insert(entity, entity); // no-op mapping
}
```
This does add additional overhead, so it may be worth pursuing alternate strategies, perhaps through a PR to Bevy itself.
Reverse the mappings for any dead entities, and apply the map again:
```rust
// At this point, the map should only contain rollback entities
debug_assert_eq!(entity_map.len(), rollback_entities.len());
// For every type that reflects `MapEntities`, map the entities so that they reference the
// new IDs after applying the snapshot.
for reflect_map_entities in type_registry
.iter() …
```
> Add a Baseline Mapping to Preserve Relationships

- Cargo.toml
- examples/box_game/box_game_p2p.rs
- examples/box_game/box_game_spectator.rs
- examples/box_game/box_game_synctest.rs
Structopt is in maintenance mode.
> Switch from `structopt` to `clap` in examples

- Cargo.toml
- examples/stress_tests/particles.rs
We need some easy way of checking for performance regressions.
- Add an example that spawns particles when either of the players holds down a key.
- Pass most parameters through command-line args
Depends on #76 and #77
> Add particles stress test

- Cargo.toml
- examples/stress_tests/particles.rs
- src/lib.rs
- src/schedule_systems.rs
- src/snapshot/component_map.rs
- src/snapshot/entity.rs
- src/snapshot/resource_map.rs
- src/snapshot/rollback_entity_map.rs
- tests/entity_mapping.rs
Bare minimum changes required to move to Bevy 0.12 from 0.11.
- Bumped Bevy to version 0.12
- Split `ComputedVisibility` into `ViewVisibility` and `InheritedVisibility`
- Updated `add_schedule` calls to use new convention
- Replaced `EntityMap` with `HashMap`
> Applied Changes as Required for Bevy 0.12

- .github/workflows/rust.yml
- src/snapshot/entity_checksum.rs
We already do this in the ggrs crate, I feel it should be done here, too.
> Feature: Add cargo fmt check to github action

- src/snapshot/entity.rs
We need to restore `Rollback` in order for entities to continue to be snapshotted and restored.
Fixes #90
> Fix desync when restoring entities

- src/lib.rs
Bevy's input systems run in `PreUpdate` in the `InputSystem` set. This ensures that the `ReadInputs` schedule runs after input is updated for the frame.
> Schedule systems after input

- examples/stress_tests/particles.rs
- src/snapshot/checksum.rs
- src/snapshot/component_checksum.rs
- src/snapshot/entity_checksum.rs
- src/snapshot/mod.rs
- src/snapshot/resource_checksum.rs
Add a `checksum_hasher` convenience function for creating bevy's `FixedState` hasher.
Makes it a little less boiler-plate heavy to add checksumming plugins (see particles example).
Bonus: If we ever want to change the hasher it's just one place.
> Add `checksum_hasher`

- src/snapshot/strategy.rs
Use `clone_from` in `CloneStrategy::update`. Could be more efficient if the user has overridden `clone_from`.
> Implement update for CloneStrategy

- examples/box_game/box_game_spectator.rs
I was getting an error due to conflicting flags, since `-h` is reserved as the short for `--help`, it can't be used as the short for `host`
```
> cargo run --example box_gam
e_spectator -- --local-port 7002 --num-players 2 --host 127
.0.0.1:7000
Compiling bevy_ggrs v0.14.0 (/home/az/dev/bevy_ggrs)
Finished dev [unoptimized + debuginfo] target(s) in 15.43s
Running `target/debug/examples/box_game_spectator --local-port 7002 --num-players 2 --host '127.0.0.1:7000'`
thread 'main' panicked at /home/az/.cargo/registry/src/index.crates.io-6f17d22bba15001f/clap_builder-4.4.18/src/builder/debug_asserts.rs:112:17:
Command bevy_ggrs: Short option names must be unique for each argument, but '-h' is in use by both 'host' and 'help' (call `cmd.disable_help_flag(true)` to remove the auto-generated …
```
> Fix example box_game_spectator.rs

- Cargo.toml
- src/rollback.rs
- src/snapshot/component_checksum.rs
- src/snapshot/entity_checksum.rs
- src/snapshot/mod.rs
This PR fixes checksum portability across different architectures by:
1. Replacing the usage of `usize` with `u64` in places where these numbers were hashed.
2. Switching the hasher implementation from the Bevy-provided, non-portable `AHash` hasher to the portable `seahash` hasher. 
Fixes https://github.com/gschup/bevy_ggrs/issues/98.
> Fix checksum portability

- Cargo.toml
- examples/box_game/box_game.rs
- examples/stress_tests/particles.rs
- src/lib.rs
- src/rollback.rs
- src/snapshot/component_map.rs
- src/snapshot/resource_map.rs
- src/snapshot/rollback_entity_map.rs
- src/time.rs
- tests/integration.rs
- Fix #105
- Bumped Bevy version to 0.13
- Updated `Input` references to `ButtonInput`
- Updated `KeyCode` values to prepend `Key` (e.g., `KeyCode::W` -> `KeyCode::KeyW`)
- Replaced `Cube` and `Plane` meshes with their new math primitives as recommended for depreciation reasons
- Explicitly converted `Color` into a `StandardMaterial` rather than relying on implicit `into()`
- Updated `AddRollbackCommandExtension` to match new lifetime generics for `EntityCommands`
- Implemented `EntityMapper` (which is now a trait instead of a type) for `RollbackEntityMap`, which will return the provided entity if it is not contained in the mapping. This ensures entities which are not tracked by the rollback map are not modified.
- Replaced the inner `HashMap` of the `RollbackEntityMap` with an …
> Update to Bevy 0.13

- Cargo.toml
- examples/box_game/box_game.rs
- examples/stress_tests/particles.rs
- src/lib.rs
- tests/entity_mapping.rs
- tests/integration.rs
This PR is an upgrade to [Bevy 0.14](https://bevyengine.org/news/bevy-0-14/).
The changes are pretty trivial, just some color changes, meshing changes, and changing `app.world` to `app.world()`/`app.world_mut()`.
> Update to Bevy 0.14
